escrutinio/core/urls.py
from django.conf.urls import url
from django.urls import path
#Import personales
from . import views, tasks

app_name = 'core'
urlpatterns = [
    #Basicas:
    url(r'^$', views.home, name='home'),

    path('contacto/', views.contacto, name='contacto'),
    path('donde_voto/', views.donde_voto, name='donde_voto'),
    #Cargas individuales
    path('cargar/<int:eleccion_id>/', views.select_acta, name='select_acta'),
    path('cargar/<int:eleccion_id>/<int:mesa_num>/', views.cargar_acta, name='cargar_acta'),
    path('subir_acta/<int:eleccion_id>/<int:mesa_num>/', views.cargar_scan, name='cargar_scan'),
    #Resultados
    path('resultados/<int:eleccion_id>/', views.resultados, name='resultados'),
    path('resultados/<int:eleccion_id>/<int:municipio_id>/', views.resultados, name='resultados'),
    path('resultados/<int:eleccion_id>/<int:municipio_id>/<int:circuito_id>', views.resultados, name='resultados'),
    #Resultados Proyectados
    path('proyectado/<int:eleccion_id>/', views.resultados, name='resultados'),
    path('proyectado/<int:eleccion_id>/<int:municipio_id>/', views.resultados, name='resultados'),
    #Resultados Proyectados Brutos
    path('proyectadobruto/<int:eleccion_id>/', views.resultados, name='resultados'),
    path('proyectadobruto/<int:eleccion_id>/<int:municipio_id>/', views.resultados, name='resultados'),
    #ranking
    path('ranking/<int:eleccion_id>/<int:cargo_id>/', views.ranking, name='ranking'),
    path('ranking/<int:eleccion_id>/<int:cargo_id>/<int:municipio_id>/', views.ranking, name='ranking'),
    #ranking proyectados
    path('rankpro/<int:eleccion_id>/<int:cargo_id>/', views.ranking, name='ranking'),
    path('rankpro/<int:eleccion_id>/<int:cargo_id>/<int:municipio_id>/', views.ranking, name='ranking'),
    #ranking proyectados Bruto
    path('rankprobruto/<int:eleccion_id>/<int:cargo_id>/', views.ranking, name='ranking'),
    path('rankprobruto/<int:eleccion_id>/<int:cargo_id>/<int:municipio_id>/', views.ranking, name='ranking'),
    #Graficos
    path('grafico/<str:cache_name>/', views.grafico, name='grafico'),
    path('grafico/<int:eleccion_id>/<int:cargo_id>/<int:municipio_id>/', views.grafico, name='grafico'),
    #Mesas Cargadas
    path('cargadas/<int:eleccion_id>/', views.mesas_cargadas, name='mesas_cargadas'),
    path('cargadas/<int:eleccion_id>/<int:municipio_id>/', views.mesas_cargadas, name='mesas_cargadas'),
    #Stat de mesas
    path('situacion_escrutinio/<int:eleccion_id>/', views.situacion_escrutinio, name='situacion_escrutinio'),
    path('situacion_escrutinio/<int:eleccion_id>/<int:municipio_id>/', views.situacion_escrutinio, name='situacion_escrutinio'),
    path('listado_mesas_csv/<int:eleccion_id>/', views.listado_mesas_csv, name='listado_mesas_csv'),
    #replicar actas
    path('replicar_actas/<int:eleccion_id>/', views.replicar_actas, name='replicar_actas'),
    path('replicar_eleccion/', views.replicar_eleccion, name='replicar_eleccion'),
    path('download_oficial/', views.download_oficiales, name='download_oficiales'),
    #Responsables
    path('cargar_resp/<int:eleccion_id>/', views.cargarresponsable, name='cargarresponsable'),
    path('responsables/<int:eleccion_id>/', views.verresponsables, name='verresponsables'),
    path('responsables/<int:eleccion_id>/<int:municipio_id>/', views.verresponsables, name='verresponsables'),
    #Controles
    path('controles/', views.controles, name='controles'),
    path('cdiferencial/', views.control_diferencial, name='control_diferencial'),
    path('cestadistico/', views.control_estadistico, name='control_estadistico'),
    path('ctotales/', views.control_nopositivos, name='control_nopositivos'),
    path('climites/', views.control_limites, name='control_limites'),
    
    #carga masiva
    path('rellenar_totales/<int:eleccion_id>/', views.rellenar_totales, name='rellenar_totales'),
    path('uploadcsv/', views.upload_csv, name='upload_csv'),
    path('uploadcsv/<str:tipo>/', views.upload_csv, name='upload_csv'),
    #Task Manager:
    path('task_progress/<str:queue_name>', tasks.task_progress, name='task_progress'),
]

escrutinio/escrutinio/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
#Import Extras
import debug_toolbar
#import personales
from core import views as coreviews

urlpatterns = [
    #Standards
    path('admin/', admin.site.urls),
    url(r'^login/$',auth_views.LoginView.as_view(template_name="extras/login.html"), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    #Extras
    url(r'^tinymce/', include('tinymce.urls')),
    path('backup/', include('backups.urls', namespace='bkups')),
    #Apps Propias
    path('', include('core.urls', namespace='core_app')),
    #Debug:
    path('__debug__/', include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

escrutinio/core/views.py
#Listado de mesas cargadas > Consistencias
#Proyeccion USAR mesas testigos y proyectando por municipio
# POST ELECCIONES:
# RE ESCRIBIR SISTEMA DE CARGOS - VOTOS PARA QUE PUEDAN IR A NACION - PROVINCIA - MUNCIPIO

#Modulos Python
import csv
import copy
import logging
from operator import itemgetter
#Modulos Django
from django.apps import apps
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Sum, Count
from django.core.cache import cache
#Agregamos modulos personales
from .decoradores import superuser_required
from .generic_classes import Charts, Items
from .models import Eleccion, Columna, Total, Cargo, CantCargos
from .models import Provincia, Municipio, Circuito
from .models import Agrupacion, Lista
from .models import Mesa, Acta, Voto, Conteo
from .models import Voto_Resumen, Conteo_Resumen
from .models import Responsable, Padron, Votante
from .modelforms import ResponsableForm, ReplicarActasForm, VotanteForm
from .functions import generar_columnas, generar_cargos, generar_listas, generar_totales
from .functions import replicar_listas
from .functions import obtener_cvotantes, proyectar, proyectar_bruto
from .functions import actualizar_resultados
from .functiones_testigo import actualizar_testigos
from .uploads import cargar_geografico, cargar_mesas, cargar_padron, cargar_votos
from .forms import ActaForm, UploadCsv, UploadPadron, UploadVotosForm, UploadMesasTestigo
from .forms import ReplicarEleccionForm, DownloadOficialesForm
from .forms import CruceDiferencial, ControlEstadistico, ControlNoPositivos, ControlxLimites
from .tasks import task_progress, crear_progress_link, download_mesas

def home(request):
    elecciones = Eleccion.objects.all()
    if elecciones:
        eleccion = elecciones.filter(activa=True).first()
    else:
        elecciones = None
    if not eleccion:
        eleccion = None
    return render(request, 'home.html', {'elecciones': elecciones, 'eleccion': eleccion, })

def contacto(request):
    return render(request, 'extras/contacto.html', {})

@staff_member_required
def controles(request):
    return render(request, 'controles/listado.html', { })

def donde_voto(request):
    if request.method == 'POST':
        form = VotanteForm(request.POST)
        if form.is_valid():
            try:
                votante = Votante.objects.get(padron__actual=True, num_doc=form.cleaned_data.get('num_doc'))
                return render(request, 'extras/votante.html', {'votante': votante,})
            except:
                return render(request, 'extras/votante.html', {'votante': None, })
    else:
        form = VotanteForm()
    return render(request, 'utils/generic_form.html', {'form': form, 'titulo_header': 'Padrón Electoral de Jujuy', })

#CARGA
@staff_member_required
def select_acta(request, eleccion_id):
    eleccion = Eleccion.objects.get(pk=eleccion_id)
    if request.method == 'POST':#Si nos envian informacion
        try:
            mesa = Mesa.objects.get(escuela__circuito__municipio__seccion__provincia__eleccion=eleccion, numero=request.POST['mesa_numero'])
        except:
            mesa = None
        if mesa is None:
            return HttpResponseRedirect("/contacto")
        else:
            return HttpResponseRedirect("/cargar/"+str(eleccion.id)+"/"+str(mesa.numero))
    return render(request, 'cargar/select_acta.html', {'eleccion': eleccion, })

@staff_member_required
def cargar_acta(request, eleccion_id, mesa_num):
    carga = False
    eleccion = Eleccion.objects.get(pk=eleccion_id)
    mesa = Mesa.objects.select_related('escuela', 'escuela__circuito', 'escuela__circuito__municipio', ).get(escuela__circuito__municipio__seccion__provincia__eleccion=eleccion, numero=mesa_num)
    acta = Acta.objects.select_related('mesa', ).get(mesa=mesa)
    header = generar_columnas(eleccion_id, 1, 3, mesa.extranjeros)#Generamosel header para (eleccion,tipo:carga,cargos:municipal)> segun tipos en models
    dict_cargos = generar_cargos(eleccion, 3, mesa.extranjeros)#Cargamos un dict-cache para evitar hits a la db
    dict_listas = generar_listas(mesa)#Cargamos un dict-cache para evitar hits a la db
    dict_totales = generar_totales(eleccion)#Cargamos un dict-cache para evitar hits a la db
    votos = Voto.objects.select_related('mesa', 'lista', 'cargo', ).filter(mesa=mesa)
    conteos = Conteo.objects.select_related('mesa', 'total', 'cargo', ).filter(mesa=mesa)
    if request.method == 'POST':#Si nos envian informacion
        votos.delete()#Borramos los votos viejos
        conteos.delete()#Borramos los conteos viejos
        votos, conteos = [], []#Creamos listas para nuevos votos y conteos
        for item in request.POST:#Por cada elemento recibido del form
            if item[:2] == "v:" and request.POST[item] and request.POST[item] != '0':#Si es un voto y no esta vacio
                lv = item[2:].split('-')#Lo parseamos
                votos.append(Voto(mesa=mesa, lista=dict_listas[int(lv[1])], cargo=dict_cargos[int(lv[2])], cantidad=int(request.POST[item])))
            if item[:2] == "t:" and request.POST[item] and request.POST[item] != '0':#Si es un conteo y no esta vacio
                lc = item[2:].split('-')#Lo parseamos
                conteos.append(Conteo(mesa=mesa, total=dict_totales[int(lc[1])], cargo=dict_cargos[int(lc[2])], cantidad=int(request.POST[item])))
        if votos or conteos:
            carga = True
            Voto.objects.bulk_create(votos)#Si se ingresaron votos, los mandamos masivamente
            Conteo.objects.bulk_create(conteos)#Si se ingresaron conteos, los mandamos masivamente
    else:
        carga = False
        votos, conteos = list(votos), list(conteos)
    return render(request, 'cargar/cargar_acta.html', {'eleccion': eleccion, 'mesa': mesa, 'header': header,
                                                       'totales':dict_totales.values(), 'listas': dict_listas.values(), 
                                                       'votos': votos, 'conteos': conteos, 'acta': acta, 'carga':carga,})

@staff_member_required
def cargar_scan(request, eleccion_id, mesa_num):
    eleccion = Eleccion.objects.get(pk=eleccion_id)
    mesa = Mesa.objects.select_related('acta', 'escuela', 'escuela__circuito', 'escuela__circuito__municipio', ).get(escuela__circuito__municipio__seccion__provincia__eleccion=eleccion, numero=mesa_num)
    if request.method == "POST":
        carga = True
        form = ActaForm(request.POST, request.FILES, instance=mesa.acta)
        if form.is_valid():
            form.save()
    else:
        carga = False
        form = ActaForm(instance=mesa.acta)
    return render(request, 'cargar/cargar_scan.html', {'eleccion': eleccion, 'mesa': mesa, 'carga': carga, 'form': form,})

#RESULTADOS
def resultados(request, eleccion_id, municipio_id=None, circuito_id=None):
    eleccion = Eleccion.objects.get(pk=eleccion_id)
    municipios = Municipio.objects.filter(seccion__provincia__eleccion=eleccion).order_by('alpha_id')
    dict_totales = generar_totales(eleccion)#Cargamos un dict-cache para evitar hits a la db
    chart = Charts()
    chart.cache_name += 'result-'
    chart.table= []#PREGUNTARLE A FISA XQ si el objeto esta recien creado trae datos viejos (?)!!!!!
    proyectado = 0

    if request.method == 'POST':
        if "id_municipio" in request.POST:
            return HttpResponseRedirect(request.path[:12]+str(eleccion.id)+"/"+str(request.POST["id_municipio"]))
        elif "id_circuito" in request.POST:
            return HttpResponseRedirect(request.path[:12]+str(eleccion.id)+"/"+str(municipio_id)+"/"+str(request.POST["id_circuito"]))

    actualizar_resultados(eleccion)
    
    if request.path[:12] == '/proyectado/':
        proyectado = 1
        chart.titulo+= ' Proyectado'
    elif request.path[:17] == '/proyectadobruto/':
        proyectado = 2
        chart.titulo+= ' Proyectado BRUTO'
    
    if circuito_id:
        municipio= Municipio.objects.get(pk=municipio_id)
        circuito = Circuito.objects.get(pk=circuito_id)
        circuitos = Circuito.objects.filter(municipio=municipio)
        chart.titulo+= ' (Circuito)'
        chart.cargo = Cargo.objects.filter(eleccion=eleccion, poder=1, tipo=3).first()
        chart.titulo+= ' para ' + chart.cargo.nombre
        header= generar_columnas(eleccion_id, 2, 3)#Generamos el header (eleccion, resultado, municipal)> segun tipos en models
        listas = Lista.objects.select_related('agrupacion').prefetch_related('cargos').filter(municipio=municipio).order_by('agrupacion__alpha_id', 'orden').distinct()
        votos = [v for v in Voto.objects.select_related('lista', 'lista__agrupacion', 'cargo', 'mesa__escuela__circuito__municipio').filter(mesa__escuela__circuito=circuito)]
        conteos = [c for c in Conteo.objects.select_related('total', 'cargo', 'mesa__escuela__circuito__municipio').filter(mesa__escuela__circuito=circuito)]
        if proyectado == 1:
            votos, conteos = proyectar(eleccion, votos, municipio, conteos)
        elif proyectado == 2:
            votos, conteos = proyectar_bruto(eleccion, votos, municipio, conteos)
        #charts:
        for lista in listas:
            chart.table.append([lista.nombre, sum(v.cantidad for v in votos if v.lista == lista and v.cargo==chart.cargo)])
        chart.table.sort(key=itemgetter(1), reverse=True)
        chart.table = [['Partido', 'Votos']] + chart.table[0:5] + [['otros', sum(cant[1] for cant in chart.table[6:])]]
        chart.cache_name += str(eleccion.id)+'-'+str(chart.cargo.id)+'-'+str(municipio.id)
        cache.set(chart.cache_name, chart)
        return render(request, 'resultados/resultados.html', {'eleccion': eleccion, 'municipio': municipio, 'circuito': circuito,
                                        'header': header, 'totales':dict_totales.values(), 'listas': listas, 

escrutinio/core/templates/cargar/cargar_acta.html
{% extends 'base.html' %}
{% load static %}
{% load table_tags %}

{% block content %}
    <div class="acta">
        <div class="informacion">
            <div class="basica col-md-4">
                <h1><b>{{eleccion.nombre}}</b>({{eleccion.fecha.date}})</h1>
                <h3><b>Escuela: </b>{{mesa.escuela.nombre}}</h3>
                <h3>
                    <b>Mesa:</b> {{mesa.numero}} 
                    {% if mesa.testigo %}
                        <b>(Testigo)</b>
                    {% endif %}
                    {%if mesa.extranjeros %}
                        <b>(Extranjeros)</b>
                    {% endif %}
                </h3>
                <h3><b>Cantidad de Electores:</b> {{acta.celectores}}</h3>
            </div>
            <div class="localizacion_carga col-md-6">
                <h3><b>Seccion: </b>{{mesa.escuela.circuito.municipio.seccion.alpha_id}}-{{mesa.escuela.circuito.municipio.seccion.nombre}}</h3>
                <h3><b>Municipio: </b>{{mesa.escuela.circuito.municipio.alpha_id}}-{{mesa.escuela.circuito.municipio.nombre}}</h3>
                <h3><b>Circuito: </b>{{mesa.escuela.circuito.alpha_id}}-{{mesa.escuela.circuito.nombre}}</h3>
            </div>
            <div class="info_extra col-md-2">
                <div>
                    <ul class='status_superior'>
                    {% if carga %}
                        <h2><li>Se Guardo con exito! <img style="width:50px;" src="{% static 'img/icons/check.png' %}"></li></h2>
                    {% endif %}
                    {% if acta.escaneado %}
                        <a href="/{{acta.escaneado.url}}" target="_blank"><li class="veracta">Ver Acta Scanneada</li></a>
                        <a href="/subir_acta/{{eleccion.id}}/{{mesa.numero}}/" target="_blank"><li class="subiracta">Remplazar Acta Scanneada</li></a>
                    {% else %}
                        <a href="/subir_acta/{{eleccion.id}}/{{mesa.numero}}/" target="_blank"><li class="subiracta">Subir Acta Scanneada</li></a>
                    {% endif %}
                    </ul>
                </div>
            </div>
        </div>
        
        <hr>

        <div class="full_tabla">
            <form action="" name="Pedido" method="POST">
            {% csrf_token %}
                <table class="tabla">
                    <thead class="cabecera">
                        <tr class="tr_header">
                            {% for columna in header %}
                                {% if columna.get_cname == 'columna' %}
                                    <th class="colfijas">{{columna.nombre}}</th>
                                {% elif columna.get_cname == 'cargo' %}
                                    <th class="colcantidades">{{columna.nombre}}</th>
                                {% endif %}
                            {% endfor %}
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="tr_vacia">
                            <td colspan="{{ header|length }}"></td>
                        </tr>
                        {% for lista in listas %}<!-- Se podrian realizar sub filas de lista para misma agrupacion -->
                            <tr class="tr_votos">
                                {% for columna in header %}
                                    {% if columna.get_cname == 'columna' %}
                                        <td class="colfijas">{% obtener_valor lista columna.show_field %}</td>
                                    {% elif columna.get_cname == 'cargo' %}
                                        {% if columna in lista.cargos.all %}
                                            <td class="input colcantidades"> <!-- Deberiamos agregar: autofocus al primero -->
                                                <input id="voto" name="v:{{mesa.id}}-{{lista.id}}-{{columna.id}}" 
                                                type="number" min="0" step="1" pattern="\d+" 
                                                value="{% obtener_votos votos lista columna %}"
                                                min="0"
                                                max="{{acta.celectores}}"/>
                                            </td>
                                        {% elif not columna.lista_field %}
                                            <td class="colcantidades"><div class="vacio">No usar</div></td>
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}
                            </tr>
                        {% endfor %}
                        <tr class="tr_vacia">
                            <td colspan="{{ header|length }}"></td>
                        </tr>
                        <!-- Se cargan filas de totales -->
                        {% for total in totales %}
                            <tr class="tr_totales {% if total.totales %}{% control_totales header votos conteos %}{% endif %}">
                                <td class="colfijas"></td>
                                <td class="colfijas" style="text-align:right;padding-right:20px;"><b>{{total.nombre}}</b></td>
                                {% for columna in header %}
                                    {% if columna.get_cname == 'cargo' %}
                                        <td class="input colcantidades">
                                            <input name="t:{{mesa.id}}-{{total.id}}-{{columna.id}}" 
                                            type="number" min="0" step="1" pattern="\d+" 
                                            value="{% obtener_conteos conteos total columna %}"
                                            min="0"
                                            max="{{acta.celectores}}"/>
                                        </td>
                                    {% endif %}
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <button class="bt_confirmar">Enviar Acta</button>
            </form>
        </div>
    </div>
    <br><br><br><br><br>
{% endblock %}

escrutinio/core/templates/cargar/cargar_scan.html
{% extends 'base.html' %}
{% load static %}
{% load table_tags %}

{% block content %}
    <div class="acta">
        <div class="localizacion" style="text-align: right;">
            {%if carga %}
                <h2><b>Se Guardo con exito! </b><img style="width:50px;" src="{% static 'img/icons/check.png' %}"></h2>
            {% endif %}
        </div>
        <div class="informacion">
            <div class="basica">
                <h1 style="float:left;"><b>{{eleccion.nombre}}</b>({{eleccion.fecha.date}})</h1>
                <h3><b>Escuela: </b>{{mesa.escuela.numero}}-{{mesa.escuela.nombre}}</h3>
                <h3><b>Mesa: </b>{{mesa.numero}} {% if mesa.testigo %}<b>(Testigo)</b>{% endif %} <a href="{% url 'core:cargar_acta' eleccion.id mesa.numero %}">(Volver al acta)</a></h3>
                <h3><b>Cantidad de Electores:</b> {{mesa.acta.celectores}}</h3>
            </div>
            <div class="localizacion">
                <h3><b>Seccion: </b>{{mesa.escuela.circuito.municipio.seccion.alpha_id}}-{{mesa.escuela.circuito.municipio.seccion.nombre}}</h3>
                <h3><b>Municipio: </b>{{mesa.escuela.circuito.municipio.alpha_id}}-{{mesa.escuela.circuito.municipio.nombre}}</h3>
                <h3><b>Circuito: </b>{{mesa.escuela.circuito.alpha_id}}-{{mesa.escuela.circuito.nombre}}</h3>
            </div>
        </div>
        <hr class="linea">
        <div class="formulario">
            {% if form %}
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Subir</button>
                </form>
            {% endif %}
        </div>
    </div>
    <br><br><br><br><br>
{% endblock %}

escrutinio/core/templates/cargar/select_acta.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="centrado">
        <form action="" method="POST" enctype="multipart/form-data" class="form-horizontal" style="margin:10px;"> 
            {% csrf_token %}
            <p>Realizar la carga del acta para Eleccion: {{ eleccion.nombre }}</p>
            <p>Mesa:</p>
            <input name="mesa_numero" type="number" min="0" step="1" pattern="\d+" value="" autofocus/>
            <div class="form-group">                    
                <div style="margin:10px;">
                    <button class="btn btn-primary"> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"></span>Cargar</button>
                </div> 
            </div>
        </form>
    </div>
{% endblock %}